"""Add api_key field to qsa_usr_user table

Revision ID: 98c636f279e8
Revises: 857a5e073750
Create Date: 2025-11-21 10:12:00.369693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import os


# revision identifiers, used by Alembic.
revision = '98c636f279e8'
down_revision = '857a5e073750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qsa_usr_user', sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # 获取环境变量中的API_KEY并设置为所有现有用户的默认值
    api_key = os.getenv('API_KEY', '')
    if api_key:
        op.execute(f"UPDATE qsa_usr_user SET api_key = '{api_key}' WHERE api_key IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qsa_usr_user', 'api_key')
    # ### end Alembic commands ###
